version: "3.8"

services:
  ollama:
    image: ollama/ollama
    container_name: ollama
    networks:
      - chatbot_network
    ports:
      - "11434:11434"

  chatbot:
    build: .
    container_name: nextjs-chatbot
    networks:
      - chatbot_network
    ports:
      - "3000:3000"
    depends_on:
      - ollama

networks:
  chatbot_network:
    driver: bridge
